Boards
kpaveliev/skypro-c06-cw06_todolist pull request #4
Opened 2022-10-30 16:39 UTC by kpaveliev

### Goals app - Board

Board - new higher level organizing element, all categories are created within boards
Users could share their boards with others with the permission to view and/or change related items (categories, goals)
and leave comments

- front version updated to lesson-37
- Board and BoardParticipant models added
- Board views added (create, list, update, destroy)
- Category, Goal, Comment logic updated respectively: querysets, permissions, validation on create
- user can view items related to the boards he's member of (owner, writer or reader)
- user can create categories, goals, comments only if he's owner/writer of the related board
- user can update, delete only if he's owner/writer of the related board
- user can update, delete only his comments
- when board, category is marked as is_deleted, all child categoris, goals are also marked as is_deleted

### Refactor

- github actions: on pull_request condition added

2022-10-31 07:40 UTC, painassasin requested changes

2022-10-31 07:40 UTC, painassasin commented on todolist/goals/admin.py
> +    readonly_fields = ("created", "updated")
Эти поля есть у всех моделей и у всех они только для чтения, кажется тут не хватает наследования)

2022-10-31 07:40 UTC, painassasin commented on todolist/goals/migrations/0008_create_new_objects.py
> +                created=timezone.now(),  # Проставляем вручную по той же причине, что описана вверху
Четыре раза получаешь текущее время, это и не оптимально и время будет отличаться немного - лучше вынести это в отдельную переменную еще перед началом контекстного менеджера

2022-10-31 07:40 UTC, painassasin commented on todolist/goals/models/goal.py
> +    class Status(models.IntegerChoices):
Зачем перенес сюда код?

2022-10-31 07:40 UTC, painassasin commented on todolist/goals/permissions.py
> +        if not request.user.is_authenticated:
Тут лучше унаследоваться от IsAuthenticated, чтобы не повторять данную строчку в каждом классе

2022-10-31 07:40 UTC, painassasin commented on todolist/goals/serializers/board.py
> +            instance.title = validated_data["title"]
title - это не обязательное поля для обновление (обновить мы можем либо title, либо участников, либо все вместе), так что тут может выскочить `KeyError`

2022-10-31 07:54 UTC, kpaveliev commented on todolist/goals/admin.py
> +    readonly_fields = ("created", "updated")
Согласен) Исправлено в этом коммите: [https://github.com/kpaveliev/skypro-c06-cw06_todolist/pull/4/commits/d7c09fa6df81f02ec9cfa5429c5eb975bedae565](url)

2022-10-31 07:57 UTC, kpaveliev commented on todolist/goals/migrations/0008_create_new_objects.py
> +                created=timezone.now(),  # Проставляем вручную по той же причине, что описана вверху
Точно! Исправлено тут: [https://github.com/kpaveliev/skypro-c06-cw06_todolist/pull/4/commits/18af2a5c5e8290323e378f3f297770a7c0d5ec23](url)

2022-10-31 08:12 UTC, kpaveliev commented on todolist/goals/models/goal.py
> +    class Status(models.IntegerChoices):
Чтобы во вьюшке Board (RetrieveUpdate) при изменении статуса дочерних целей обращаться к нужному вот так Goal.Status.archived, а не импортировать отдельно Status и обращаться Status.archived

[https://github.com/kpaveliev/skypro-c06-cw06_todolist/blob/boards/todolist/goals/views/board.py#:~:text=Goal.objects.filter(category__board%3Dinstance).,)](url)

Ну и для приведения в соответствие с моделью BoardParticipant (там класс с Ролями тоже живет внутри класса), и как-будто это логичнее

2022-10-31 08:21 UTC, kpaveliev commented on todolist/goals/permissions.py
> +        if not request.user.is_authenticated:
Согласен! Исправлено тут: [https://github.com/kpaveliev/skypro-c06-cw06_todolist/pull/4/commits/62f852d4d151f434f0fa0c0edca2ec8caaaebc4c](url)

2022-10-31 08:44 UTC, kpaveliev commented on todolist/goals/permissions.py
> +        if not request.user.is_authenticated:
И правда надо убедиться, поправил тут: [https://github.com/kpaveliev/skypro-c06-cw06_todolist/pull/4/commits/024cf2a3e8494ccff91eded6603e3fd83dc07865](url)

2022-10-31 08:44 UTC, kpaveliev commented on todolist/goals/serializers/board.py
> +            instance.title = validated_data["title"]
И правда надо убедиться, поправил тут: [https://github.com/kpaveliev/skypro-c06-cw06_todolist/pull/4/commits/024cf2a3e8494ccff91eded6603e3fd83dc07865](https://github.com/kpaveliev/skypro-c06-cw06_todolist/pull/url)

2022-11-01 07:18 UTC, painassasin approved these changes

2022-11-01 07:22 UTC, merged